// AUTO-GENERATED by scripts/import-la-history-data.mjs.
// Do not edit by hand — re-run the importer instead.

import type { Era, EraKey } from '@/types/laHistory';

export const eras = [
  {
    "key": "native",
    "order": 1,
    "name": "Tongva (Native)",
    "shortLabel": "Native",
    "description": "Indigenous Tongva life across the LA Basin before European contact — villages, trade networks, and a landscape shaped by careful stewardship.",
    "accentColor": "#7c8d65"
  },
  {
    "key": "spanish",
    "order": 2,
    "name": "Spanish",
    "shortLabel": "Spanish",
    "description": "Mission expansion, the founding of El Pueblo, and the reshaping of Tongva life under Spanish colonial rule.",
    "accentColor": "#b8845f"
  },
  {
    "key": "rancho",
    "order": 3,
    "name": "Rancho",
    "shortLabel": "Rancho",
    "description": "Mexican land grants and cattle ranching after secularization — a brief era that left a deep imprint on LA geography.",
    "accentColor": "#9a6b4a"
  },
  {
    "key": "modern",
    "order": 4,
    "name": "Modern",
    "shortLabel": "Modern",
    "description": "American statehood, water engineering, mass migration, infrastructure, and the conflicts that built the city we know.",
    "accentColor": "#5b7b9a"
  }
] as const satisfies readonly Era[];

export const eraByKey = new Map<EraKey, Era>(eras.map((e) => [e.key as EraKey, e]));
export const eraByOrder = new Map<number, Era>(eras.map((e) => [e.order, e]));
