// AUTO-GENERATED by scripts/import-la-history-data.mjs.
// Do not edit by hand — re-run the importer instead.

import type { Quiz } from '@/types/laHistory';

export const quizzes = [
  {
    "locationSlug": "kuruvungna-springs",
    "title": "The Tongva at Kuruvungna",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What does the name 'Kuruvungna' mean in the Tongva language?",
        "questionType": "multiple_choice",
        "optionA": "A place near the water",
        "optionB": "Sacred ground of the elders",
        "optionC": "A place where we are in the sun",
        "optionD": "The meeting of two rivers",
        "correctAnswer": "c",
        "explanation": "Kuruvungna means 'a place where we are in the sun.' The name reflects how the Tongva embedded their relationship with the landscape — including its quality of light — directly into language.",
        "wrongExplanationA": "Although a freshwater spring sat at the heart of the village, the Tongva name itself describes a quality of sunlight, not proximity to water.",
        "wrongExplanationB": "Kuruvungna was indeed a sacred site, but the name encodes a sensory quality of the place — not a reference to elders or leadership.",
        "wrongExplanationD": "Kuruvungna sat near streams flowing from the mountains, but the name does not describe a confluence of waterways.",
        "orderIndex": 0
      },
      {
        "questionText": "What materials did the Tongva use to build their dome-shaped homes, called 'ap'?",
        "questionType": "multiple_choice",
        "optionA": "Cedar planks and stone",
        "optionB": "Adobe mud and straw",
        "optionC": "Oak timber and clay",
        "optionD": "Willow branches and tule reeds",
        "correctAnswer": "d",
        "explanation": "The Tongva built dome-shaped 'ap' homes from willow branches and tule reeds. These materials were abundant near springs and wetlands and were designed to breathe with the coastal air.",
        "wrongExplanationA": "Cedar planks were associated with Pacific Northwest peoples, not the Tongva of Southern California — and the LA Basin's ecology supplied lighter, more flexible materials.",
        "wrongExplanationB": "Adobe construction was a Spanish colonial technique introduced after 1771 — long after the Tongva had developed their own tradition of organic, breathable shelters.",
        "wrongExplanationC": "Oak provided acorns for food, but the Tongva did not build homes from oak timber — they relied on flexible willow and tule that could form a dome easily.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The Tongva used shell beads as part of a trade network that stretched across long distances.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. Shell beads were a key part of Tongva trade, moving across regional networks that also carried obsidian, dried fish, and plant medicines.",
        "wrongExplanationB": "Shell beads are well documented as exchange items in Tongva and neighboring trade networks — they linked coastal, basin, and desert peoples across long distances.",
        "orderIndex": 2
      },
      {
        "questionText": "Why was the spring at Kuruvungna so important to village life?",
        "questionType": "multiple_choice",
        "optionA": "It was believed to have healing powers",
        "optionB": "It provided water year-round",
        "optionC": "It connected to the ocean",
        "optionD": "It was used only for ceremonies",
        "correctAnswer": "b",
        "explanation": "The spring flowed steadily year-round, which is why families could live, gather, and raise children there for thousands of years. Reliable water was the foundation of village life.",
        "wrongExplanationA": "The spring was sacred, but the source description points to its year-round flow — practical reliability, not specific healing properties — as the reason it anchored the village.",
        "wrongExplanationC": "Kuruvungna was inland — near where hills and ocean worlds met — but the spring itself did not connect to the sea.",
        "wrongExplanationD": "Ceremonies took place at the spring, but the site was also home to daily life: cooking, raising children, and gathering. Limiting it to ceremony alone misses what made it central.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "ballona-wetlands",
    "title": "Ballona Wetlands and Tongva Coastal Life",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What did the Tongva use tule reeds for?",
        "questionType": "multiple_choice",
        "optionA": "Trade with distant villages only",
        "optionB": "Baskets and homes",
        "optionC": "Building canoes",
        "optionD": "Storing acorns",
        "correctAnswer": "b",
        "explanation": "Tule reeds were one of the most versatile wetland resources — used to weave baskets and to construct dome-shaped 'ap' homes.",
        "wrongExplanationA": "Tule reeds were a daily-use material, not a long-distance trade good. The Tongva harvested and worked them locally for everyday needs.",
        "wrongExplanationC": "Plank canoes used wood planks sewn together with plant fiber and sealed with tar — not tule reeds, which were too soft to handle ocean travel.",
        "wrongExplanationD": "Acorns were typically stored in granaries or woven baskets, but tule's primary uses were construction and weaving — not as storage vessels themselves.",
        "orderIndex": 0
      },
      {
        "questionText": "What mainly caused Ballona Wetlands to shrink during the twentieth century?",
        "questionType": "multiple_choice",
        "optionA": "Flood channels and development",
        "optionB": "A major drought",
        "optionC": "Sea level rise",
        "optionD": "Overhunting by the Tongva",
        "correctAnswer": "a",
        "explanation": "Twentieth-century flood control projects and real estate development drained and reshaped most of Ballona's original 2,900 acres, leaving only a small remnant.",
        "wrongExplanationB": "Drought may strain wetlands temporarily, but Ballona's loss was driven by deliberate engineering — channelizing creeks and filling marshland for development.",
        "wrongExplanationC": "Sea level change is a long-term factor, but Ballona's twentieth-century shrinkage was a direct result of human construction, not rising seas.",
        "wrongExplanationD": "The Tongva managed Ballona sustainably for thousands of years. The wetlands declined only after twentieth-century development — long after Tongva life was disrupted.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The Tongva built plank canoes to travel across the ocean to nearby islands.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. The Tongva built plank canoes that carried people and goods across the ocean to nearby islands, treating the coast as a pathway rather than an edge.",
        "wrongExplanationB": "Tongva ocean-going plank canoes are well documented, used to reach the Channel Islands and to carry trade goods up and down the coast.",
        "orderIndex": 2
      },
      {
        "questionText": "How large was Ballona Wetlands historically?",
        "questionType": "multiple_choice",
        "optionA": "Nearly 500 acres",
        "optionB": "Nearly 5,000 acres",
        "optionC": "Nearly 1,200 acres",
        "optionD": "Nearly 2,900 acres",
        "correctAnswer": "d",
        "explanation": "Ballona Wetlands historically covered nearly 2,900 acres of marsh, reeds, and flowing water — a vast coastal ecosystem that has since been reduced to a small remnant.",
        "wrongExplanationA": "500 acres is far smaller than the historical wetland — closer to the size of remaining fragments today than the original ecosystem.",
        "wrongExplanationB": "5,000 acres overshoots the historical figure. Ballona was vast but not that large at its peak.",
        "wrongExplanationC": "1,200 acres falls short of the original extent. The wetlands stretched nearly 2,900 acres before twentieth-century development.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "san-gabriel-foothills",
    "title": "Tongva Lifeways in the Foothills",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "How did the Tongva prepare acorns from oak trees?",
        "questionType": "multiple_choice",
        "optionA": "Ate them raw after soaking",
        "optionB": "Dried them for trade only",
        "optionC": "Boiled them whole in clay pots",
        "optionD": "Ground them into flour using stone mortars",
        "correctAnswer": "d",
        "explanation": "The Tongva ground acorns into flour with stone mortars, then leached the bitter tannins and turned the flour into porridge or bread. Many of these grinding stones still survive in the foothills today.",
        "wrongExplanationA": "Raw acorns are bitter and even toxic due to tannins. The Tongva developed a careful processing tradition — grinding, leaching, and cooking — to make them edible.",
        "wrongExplanationB": "Acorns were a dietary staple, not just a trade good. They fed families through the year, especially in autumn when the harvest came in.",
        "wrongExplanationC": "Boiling acorns whole would not remove their tannins. The standard practice was grinding to flour, then leaching the flour with water to remove bitterness.",
        "orderIndex": 0
      },
      {
        "questionText": "What is implied when the Spanish admired the land's richness without recognizing Tongva management?",
        "questionType": "multiple_choice",
        "optionA": "They fully respected Tongva stewardship",
        "optionB": "They mistook cultivated land for untouched wilderness",
        "optionC": "They found the land empty and poor",
        "optionD": "They only wanted trade partnerships",
        "correctAnswer": "b",
        "explanation": "Tongva villages had shaped the foothills for generations through controlled burning, oak grove management, and seasonal harvest. The Spanish saw abundance but read it as wild nature, missing the human work that produced it.",
        "wrongExplanationA": "Spanish accounts admired the land's richness but did not credit the Tongva for it — the failure to recognize Indigenous stewardship is precisely the problem the question highlights.",
        "wrongExplanationC": "The Portolá Expedition specifically noted the land's fertility and large settlements. The Spanish did not see emptiness; they saw abundance — and misread its source.",
        "wrongExplanationD": "Trade partnerships were not the framework of Spanish colonization in California. Within two years of the expedition, Mission San Gabriel was founded — colonization, not partnership.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Tongva villages in the foothills were located near streams flowing down from the mountains.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. Tongva villages in the San Gabriel foothills were placed deliberately near mountain streams, providing reliable water and access to seasonal resources.",
        "wrongExplanationB": "Reliable streams from the mountains were essential for Tongva village life, supporting drinking water, food preparation, and seasonal harvest.",
        "orderIndex": 2
      },
      {
        "questionText": "What does the contrast between thousands of years of knowledge and rapid loss suggest?",
        "questionType": "multiple_choice",
        "optionA": "Colonization was gradual and harmless",
        "optionB": "Knowledge systems can be destroyed faster than they are built",
        "optionC": "Knowledge always disappears naturally",
        "optionD": "Tongva knowledge had little value",
        "correctAnswer": "b",
        "explanation": "Tongva knowledge of the foothills was built carefully over thousands of years and disrupted within a generation of mission founding. The contrast highlights how fragile long-developed knowledge systems can be under colonization.",
        "wrongExplanationA": "The mission system caused devastating disruption — population loss, forced labor, and the breakdown of village life. None of this was harmless or gradual.",
        "wrongExplanationC": "Knowledge does not disappear naturally — Tongva knowledge was disrupted by specific colonial policies and institutions, not by some inevitable process.",
        "wrongExplanationD": "Tongva knowledge supported a sustainable society for thousands of years. Its loss is a tragedy precisely because of its depth and value.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "el-pueblo",
    "title": "The Founding of Los Angeles",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "The settlers who founded Los Angeles came from many different racial and cultural backgrounds. What does this tell us about the city's origins?",
        "questionType": "multiple_choice",
        "optionA": "Los Angeles was founded as an exclusively Spanish colony",
        "optionB": "The founding was more diverse than most people realize",
        "optionC": "Only Indigenous people played a role in building the city",
        "optionD": "The settlers all shared the same culture and traditions",
        "correctAnswer": "b",
        "explanation": "The 44 founding pobladores came from Sonora and Sinaloa and represented Indigenous, African, and Spanish ancestry — reflecting the mixed demographics of New Spain's frontier.",
        "wrongExplanationA": "The settlers were not exclusively Spanish — they were a mixed group recruited from frontier provinces, with most born in New Spain rather than in Spain itself.",
        "wrongExplanationC": "Indigenous people were among the founders, but the group also included settlers of African and Spanish heritage. Crediting any single group alone misses the documented diversity.",
        "wrongExplanationD": "The settlers came from different regions and backgrounds with distinct family histories. Treating them as culturally uniform erases the documented complexity of the founding.",
        "orderIndex": 0
      },
      {
        "questionText": "Why was the central plaza important to the pueblo?",
        "questionType": "multiple_choice",
        "optionA": "It served as the center of community life, government, and trade",
        "optionB": "It was used only for religious ceremonies",
        "optionC": "It was built to honor the original Tongva inhabitants",
        "optionD": "It was only used by Spanish military leaders",
        "correctAnswer": "a",
        "explanation": "Like other Spanish colonial settlements, the plaza was the civic heart of the pueblo — the place where community life, government, and trade all converged, while also expressing colonial order on the land.",
        "wrongExplanationB": "Religious life was important at the plaza, but it also hosted government, daily commerce, and gatherings. Limiting it to ceremony misses its central civic role.",
        "wrongExplanationC": "The plaza was a colonial design imposed on the landscape. It was not built to honor Tongva inhabitants whose lives the colonial project was actively disrupting.",
        "wrongExplanationD": "The plaza was a civilian town's center, open to settlers and used for commerce and community life — not a restricted military space.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The pueblo was founded while Alta California was under Spanish colonial rule.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. Los Angeles was founded in 1781 as part of New Spain. It did not become Mexican territory until Mexican independence in 1821.",
        "wrongExplanationB": "In 1781, Alta California was firmly part of the Spanish colonial empire. Mexico did not gain independence from Spain until 1821 — forty years after the pueblo's founding.",
        "orderIndex": 2
      },
      {
        "questionText": "When Mexico gained independence in 1821, the plaza remained the center of the settlement. What does this suggest?",
        "questionType": "multiple_choice",
        "optionA": "Mexico and Spain governed in exactly the same way",
        "optionB": "The settlers rejected Mexican rule entirely",
        "optionC": "Some things in daily life stayed the same even as governments changed",
        "optionD": "Independence immediately transformed every aspect of the pueblo",
        "correctAnswer": "c",
        "explanation": "Political authority shifted from Spain to Mexico, but the plaza, the homes, and the rhythms of daily life carried on. Continuity at the local level often outlasts changes at the top.",
        "wrongExplanationA": "Mexican governance differed from Spanish rule in important ways — including the eventual secularization of the missions. Continuity of the plaza does not mean identical government.",
        "wrongExplanationB": "The pueblo became part of Mexico without rejecting Mexican rule — its residents were largely Mexican-born already.",
        "wrongExplanationD": "Independence did not transform every aspect of pueblo life overnight. The continuing role of the plaza shows just how much daily life persisted across regimes.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "mission-san-gabriel",
    "title": "Mission San Gabriel and the Mission System",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What happened to Tongva people under mission control?",
        "questionType": "multiple_choice",
        "optionA": "They were baptized, renamed, and required to live and work under mission control",
        "optionB": "They were given land and allowed to govern themselves",
        "optionC": "They traded freely with the mission and maintained their independence",
        "optionD": "They were forced to leave the region entirely",
        "correctAnswer": "a",
        "explanation": "Tongva people brought into the mission system were baptized, given Spanish names, and required to live and labor inside the mission — a process that transformed identity, family life, and labor.",
        "wrongExplanationB": "Far from self-governance, Tongva people inside the mission were subject to strict religious and labor discipline. Land was held by the mission, not granted to Indigenous communities.",
        "wrongExplanationC": "The mission system was not a trading partnership. It absorbed Tongva people into a coercive religious and labor structure, not an independent commercial relationship.",
        "wrongExplanationD": "Tongva people were not forced out of the region — they were forced into the mission system itself, which is what made population loss within those walls so devastating.",
        "orderIndex": 0
      },
      {
        "questionText": "What caused devastating population loss among Indigenous communities at the mission?",
        "questionType": "multiple_choice",
        "optionA": "Warfare with neighboring villages",
        "optionB": "Forced relocation to other missions",
        "optionC": "Crowded conditions and disease",
        "optionD": "Drought and famine",
        "correctAnswer": "c",
        "explanation": "Crowded mission quarters created ideal conditions for the spread of European diseases against which Indigenous communities had no immunity. The toll on Tongva populations was catastrophic.",
        "wrongExplanationA": "Inter-village warfare was not the driver of mission-era population loss. The cause was disease in close quarters, paired with disrupted traditional food and family systems.",
        "wrongExplanationB": "Movement between missions occurred but did not by itself produce mass mortality. The decisive factor was disease in densely populated mission settings.",
        "wrongExplanationD": "Drought and famine added stress, but the proximate cause of the population collapse was epidemic disease in crowded mission communities.",
        "orderIndex": 1
      },
      {
        "questionText": "What did Mexico do to the missions in 1833?",
        "questionType": "multiple_choice",
        "optionA": "Expanded their power and gave them more land",
        "optionB": "Returned all mission land to Native communities",
        "optionC": "Burned them down and removed the church entirely",
        "optionD": "Secularized them, ending church control over their land",
        "correctAnswer": "d",
        "explanation": "In 1833, Mexico secularized the missions, ending church control over much of their land. In practice, however, the land flowed to private ranch owners rather than to the Native communities whose labor had built mission wealth.",
        "wrongExplanationA": "Secularization was specifically about reducing the missions' power, not expanding it. Mexico's policy aimed to break church dominance over land and labor.",
        "wrongExplanationB": "Although secularization promised to free Indigenous neophytes, the land was overwhelmingly transferred to private ranch owners — Native communities saw very little of it.",
        "wrongExplanationC": "Secularization was a legal and administrative shift, not a destruction of buildings. Mission San Gabriel's church still stands today.",
        "orderIndex": 2
      },
      {
        "questionText": "True or False: The mission's wealth came partly from organized agriculture and access to Indigenous labor.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. Mission San Gabriel's productivity in crops, cattle, and wine rested on organized agriculture sustained by the coerced labor of Tongva people drawn into the mission system.",
        "wrongExplanationB": "Mission wealth in California depended directly on Indigenous labor. Erasing that connection misrepresents how mission economies actually functioned.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "fort-moore-hill",
    "title": "The American Takeover of Los Angeles",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "Why was raising the flag on July 4 symbolically important?",
        "questionType": "multiple_choice",
        "optionA": "It was a random date chosen by chance",
        "optionB": "It linked conquest to American ideals",
        "optionC": "It marked a new political era for the city",
        "optionD": "Only July 4 ceremonies were allowed under wartime law",
        "correctAnswer": "c",
        "explanation": "Raising the American flag at Fort Moore on July 4, 1847, marked a new political era for Los Angeles — the formal arrival of American authority over a city that had been Mexican.",
        "wrongExplanationA": "The choice of July 4 was deliberate, not random. Independence Day carried clear political meaning that U.S. forces wanted to attach to their occupation.",
        "wrongExplanationB": "The date did connect conquest to symbols of American identity, but the most direct point of the ceremony was political — marking the start of a new era of authority over the city.",
        "wrongExplanationD": "There was no rule restricting ceremonies to July 4. The choice reflected a political message, not a legal requirement.",
        "orderIndex": 0
      },
      {
        "questionText": "Why was the fort eventually abandoned?",
        "questionType": "multiple_choice",
        "optionA": "It was destroyed in a battle",
        "optionB": "Military officials saw little need for a permanent fortification",
        "optionC": "The Mexican army recaptured the hill",
        "optionD": "A fire burned it to the ground",
        "correctAnswer": "b",
        "explanation": "Military officials concluded that a permanent fortification was unnecessary as American control over Los Angeles was secured. The fort was abandoned within a few years of being built.",
        "wrongExplanationA": "Fort Moore was not destroyed in combat. It was simply judged unnecessary once American authority was established in the city.",
        "wrongExplanationC": "After the Treaty of Guadalupe Hidalgo in 1848, California was U.S. territory. The Mexican army did not recapture Los Angeles or the hill.",
        "wrongExplanationD": "There is no record of a fire ending the fort. It was decommissioned because military officials decided it was no longer needed.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Fort Moore was a major military site for decades.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The fort was short-lived — built in 1847 and abandoned only a few years later. Its symbolic meaning, however, far outlasted its physical presence.",
        "wrongExplanationA": "Fort Moore operated for only a few years before being abandoned. It is remembered for what it symbolized, not for any long military life.",
        "orderIndex": 2
      },
      {
        "questionText": "What did the Treaty of Guadalupe Hidalgo in 1848 officially do?",
        "questionType": "multiple_choice",
        "optionA": "Ended Spanish rule over California",
        "optionB": "Returned land to Native communities",
        "optionC": "Established Los Angeles as a city",
        "optionD": "Made California part of the United States",
        "correctAnswer": "d",
        "explanation": "The Treaty of Guadalupe Hidalgo, signed in 1848, ended the Mexican-American War and made California part of the United States — bringing new laws, language, and land systems to families who had lived under Spanish and Mexican rule.",
        "wrongExplanationA": "Spanish rule over California ended in 1821 when Mexico won independence — more than two decades before the treaty was signed.",
        "wrongExplanationB": "The treaty did not return land to Native communities. In fact, the new American legal regime created new pressures on Indigenous and Mexican landholders alike.",
        "wrongExplanationC": "Los Angeles had been a pueblo since 1781 — its existence as a settlement long predated the treaty.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "old-chinatown",
    "title": "Los Angeles's Original Chinatown",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "Why did many Chinese immigrants come to Los Angeles in the 1870s?",
        "questionType": "multiple_choice",
        "optionA": "They had previously worked on the transcontinental railroad",
        "optionB": "They were invited by the Spanish government",
        "optionC": "They came to work at Mission San Gabriel",
        "optionD": "They were fleeing a major drought in China",
        "correctAnswer": "a",
        "explanation": "Many Chinese immigrants who settled near the Los Angeles Plaza in the 1870s had previously worked on the transcontinental railroad, then sought economic opportunities further south.",
        "wrongExplanationB": "Spanish rule had ended decades earlier, and the Spanish government had no role in inviting Chinese immigrants. The migration of the 1870s was tied to railroad labor markets.",
        "wrongExplanationC": "Mission San Gabriel had been secularized in 1833 and was no longer the labor center it had been. Chinese immigrants did not come to work there.",
        "wrongExplanationD": "Economic hardship played a role for many migrants, but the specific 1870s wave to Los Angeles is most directly tied to railroad construction and its aftermath.",
        "orderIndex": 0
      },
      {
        "questionText": "Why was the neighborhood especially important to Chinese residents?",
        "questionType": "multiple_choice",
        "optionA": "It was the wealthiest area in Los Angeles",
        "optionB": "They had limited places where they were allowed to live",
        "optionC": "It was the only place with access to the railroad",
        "optionD": "The city government provided them special protections there",
        "correctAnswer": "b",
        "explanation": "Discrimination and exclusion sharply limited where Chinese residents could live. Chinatown therefore became an essential refuge — a place where business, family, and community life could persist together.",
        "wrongExplanationA": "Chinatown was not a wealthy district. Its importance came from being one of the few places where Chinese residents were able to live and build community at all.",
        "wrongExplanationC": "Several parts of the city had access to the railroad. Chinese settlement near the Plaza was driven by community ties and limited housing options, not exclusive rail access.",
        "wrongExplanationD": "The city did not extend special protections to Chinese residents — the 1871 mass attack and the 1933 demolition both demonstrate the opposite. The neighborhood mattered because of community, not state protection.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Chinese immigrants began settling near the Los Angeles Plaza in the 1870s.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "a",
        "explanation": "True. Chinese immigrants began building a neighborhood near the Plaza in the 1870s, after many had worked on the transcontinental railroad.",
        "wrongExplanationB": "The community formed in the 1870s near the original Los Angeles Plaza, growing into the neighborhood later known as Old Chinatown.",
        "orderIndex": 2
      },
      {
        "questionText": "Why was Old Chinatown condemned in 1933?",
        "questionType": "multiple_choice",
        "optionA": "It was destroyed in a fire",
        "optionB": "The city wanted to build a new city hall",
        "optionC": "To make way for Union Station",
        "optionD": "Residents chose to relocate voluntarily",
        "correctAnswer": "c",
        "explanation": "The city condemned Old Chinatown to clear the land for Union Station. Residents and businesses were displaced, and the community rebuilt several blocks away as New Chinatown.",
        "wrongExplanationA": "Old Chinatown was demolished by city order, not destroyed by fire. The displacement was deliberate, not accidental.",
        "wrongExplanationB": "City Hall already existed and was not the project that displaced Chinatown. The land was cleared for a major new train station.",
        "wrongExplanationD": "Residents and businesses were forced out by condemnation, not relocating by choice. They rebuilt elsewhere because they had no option to stay.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "bradbury-building",
    "title": "LA's Boom Era and the Bradbury Building",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What makes the Bradbury Building's exterior unusual compared to its interior?",
        "questionType": "multiple_choice",
        "optionA": "The exterior is colorful while the interior is plain",
        "optionB": "The exterior is plain while the interior is filled with ornate details",
        "optionC": "The exterior is made of glass while the interior is made of adobe",
        "optionD": "The exterior is modern while the interior is medieval",
        "correctAnswer": "b",
        "explanation": "The Bradbury Building's modest exterior gives little hint of what's inside: a soaring atrium full of ornate ironwork, open elevators, skylights, and natural light. The contrast is part of what makes it iconic.",
        "wrongExplanationA": "The relationship is reversed — the plain side faces the street, while the elaborate detailing waits inside.",
        "wrongExplanationC": "The Bradbury is a brick-and-iron commercial building, not a glass-and-adobe hybrid. The contrast that matters is plainness outside, ornate detail inside.",
        "wrongExplanationD": "Both exterior and interior are products of the late nineteenth century. The contrast is in ornamentation, not in time period.",
        "orderIndex": 0
      },
      {
        "questionText": "Who designed much of the Bradbury Building's striking interior?",
        "questionType": "multiple_choice",
        "optionA": "Lewis Bradbury",
        "optionB": "A Spanish colonial designer",
        "optionC": "Union Station architects",
        "optionD": "George Wyman",
        "correctAnswer": "d",
        "explanation": "Draftsman George Wyman designed much of the Bradbury Building's celebrated interior. The result was unlike anything else in Los Angeles at the time.",
        "wrongExplanationA": "Lewis Bradbury commissioned the building, but he did not design its interior — that work was George Wyman's.",
        "wrongExplanationB": "The Bradbury Building belongs to the late nineteenth-century commercial era, not the Spanish colonial period. Its design was firmly American Gilded Age.",
        "wrongExplanationC": "Union Station was built decades later by different architects and has no design connection to the Bradbury Building.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The Bradbury Building was demolished during a period of redevelopment in the twentieth century.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The Bradbury Building has survived economic shifts and redevelopment and remains standing on Broadway as one of LA's most celebrated historic structures.",
        "wrongExplanationA": "The Bradbury Building was not demolished — it remains a working historic landmark in downtown Los Angeles.",
        "orderIndex": 2
      },
      {
        "questionText": "What was driving the rapid growth of Los Angeles when the Bradbury Building was constructed?",
        "questionType": "multiple_choice",
        "optionA": "The discovery of gold nearby",
        "optionB": "The founding of new missions",
        "optionC": "Railroad expansion and land speculation",
        "optionD": "A large wave of immigration from China",
        "correctAnswer": "c",
        "explanation": "Railroad expansion and aggressive land speculation drove a population boom in late-nineteenth-century Los Angeles, transforming the city into a major commercial center — exactly the climate that produced the Bradbury Building.",
        "wrongExplanationA": "The major California gold rush was decades earlier and centered in Northern California. It was not the driver of LA's 1880s–1890s boom.",
        "wrongExplanationB": "The mission system had been secularized in 1833. By the 1890s, growth was driven by railroads and real estate, not mission founding.",
        "wrongExplanationD": "Chinese immigration shaped the city, but the broader population boom that fueled commercial development came from railroads and land promotion drawing migrants from across the country.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "hollenbeck-park",
    "title": "Boyle Heights and Hollenbeck Park",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What distinction does Hollenbeck Park hold in Los Angeles history?",
        "questionType": "multiple_choice",
        "optionA": "It was the largest park ever built in California",
        "optionB": "It was the first park to have a public lake",
        "optionC": "It was Los Angeles's first public park",
        "optionD": "It was the first park built specifically for immigrant communities",
        "correctAnswer": "c",
        "explanation": "Hollenbeck Park, opened in 1892, became Los Angeles's first public park — a milestone in the city's civic life and a foundation for what would become the LA park system.",
        "wrongExplanationA": "Hollenbeck Park is not the largest park in California — Griffith Park, donated four years later, is far bigger. Hollenbeck's distinction is being first, not biggest.",
        "wrongExplanationB": "While the lake is iconic, what makes Hollenbeck historically significant is that it was the city's first public park, not a specific feature like its lake.",
        "wrongExplanationD": "Hollenbeck Park was a general public park. It was not designed specifically for immigrant communities — it became important to them because of who lived in Boyle Heights.",
        "orderIndex": 0
      },
      {
        "questionText": "Why did many diverse communities end up living near Hollenbeck Park in Boyle Heights?",
        "questionType": "multiple_choice",
        "optionA": "The land was cheaper because it flooded regularly",
        "optionB": "It was the only neighborhood near railroad jobs",
        "optionC": "The city government assigned immigrants to live there",
        "optionD": "Other neighborhoods excluded them",
        "correctAnswer": "d",
        "explanation": "Restrictive covenants and other forms of housing discrimination shut Jewish, Japanese, Mexican, Russian Molokan, and African American families out of much of Los Angeles. Boyle Heights — open in ways other neighborhoods were not — became a rare home.",
        "wrongExplanationA": "Flooding wasn't the central reason. Communities settled in Boyle Heights primarily because exclusion elsewhere left them few alternatives.",
        "wrongExplanationB": "Many neighborhoods had access to railroad work. The defining factor in Boyle Heights was housing access — who could live where, given racial covenants in other areas.",
        "wrongExplanationC": "There was no government program assigning immigrants to Boyle Heights. Settlement patterns reflected exclusion from other neighborhoods, not assignment.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Hollenbeck Park was named after Elizabeth Hollenbeck, who donated the land.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. Elizabeth Hollenbeck donated the land, but the park was named in memory of her late husband — the donation was a memorial gift.",
        "wrongExplanationA": "Elizabeth Hollenbeck did make the donation, but the park's name honors her husband. The naming reflects the memorial nature of the gift, not the donor herself.",
        "orderIndex": 2
      },
      {
        "questionText": "What made the park's lake and open space significant to the community?",
        "questionType": "multiple_choice",
        "optionA": "It was used exclusively for religious ceremonies",
        "optionB": "It provided a shared gathering place for communities with different languages and traditions",
        "optionC": "It was the only source of fresh water in the neighborhood",
        "optionD": "It was reserved for wealthy residents of the city",
        "correctAnswer": "b",
        "explanation": "In a city marked by social divisions, Hollenbeck Park offered something rare: shared public space where Boyle Heights's many communities could gather across language, religion, and tradition.",
        "wrongExplanationA": "Hollenbeck was a public park, not a religious site. Its value was in being open and shared across many different communities.",
        "wrongExplanationC": "The lake added beauty but was not the neighborhood's water supply. Its meaning was social: a place to gather, not a utility.",
        "wrongExplanationD": "The whole point of a public park was that it was open to everyone, not reserved for wealthy residents. That openness is what made it significant.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "la-placita-church",
    "title": "La Placita and the Latino Catholic Tradition",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What makes the current adobe structure of La Placita Church historically significant?",
        "questionType": "multiple_choice",
        "optionA": "It is the oldest surviving church in Los Angeles",
        "optionB": "It is the largest church ever built in California",
        "optionC": "It was built by the Tongva people before Spanish arrival",
        "optionD": "It was personally designed by a Spanish king",
        "correctAnswer": "a",
        "explanation": "Completed in 1822, the current adobe church is the oldest surviving church building in Los Angeles — a physical link from the Mexican period to the present-day city.",
        "wrongExplanationB": "La Placita is historically significant for its age, not its size. Other California churches are larger.",
        "wrongExplanationC": "The Tongva did not build churches — La Placita was a colonial Catholic chapel established in 1784, after Spanish missionization had already begun.",
        "wrongExplanationD": "Spanish kings did not personally design colonial chapels. La Placita was built by local labor under church direction during the Mexican period.",
        "orderIndex": 0
      },
      {
        "questionText": "Which institution was La Placita Church closely tied to during the colonial era?",
        "questionType": "multiple_choice",
        "optionA": "Fort Moore",
        "optionB": "The Los Angeles pueblo government",
        "optionC": "Mission San Gabriel",
        "optionD": "The Mexican army",
        "correctAnswer": "c",
        "explanation": "During the colonial era, La Placita was closely tied to Mission San Gabriel — the regional center of the Franciscan mission system that shaped religious life across the LA region.",
        "wrongExplanationA": "Fort Moore was a U.S. military post built in 1847 — long after La Placita's colonial-era origins. The two belong to entirely different periods and systems.",
        "wrongExplanationB": "The pueblo government was a civilian institution, while La Placita's colonial-era ties were primarily religious — anchored in Mission San Gabriel.",
        "wrongExplanationD": "The Mexican army existed only after Mexican independence in 1821. La Placita's earliest decades pre-date the Mexican era and were tied to the Franciscan mission system.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The current La Placita church building was completed in the 20th century.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The present adobe church was completed in 1822, during the Mexican period — making it the oldest surviving church in Los Angeles, well before the 20th century began.",
        "wrongExplanationA": "The current building dates to 1822, not the 20th century. That early date is exactly what makes it the oldest surviving church in the city.",
        "orderIndex": 2
      },
      {
        "questionText": "What kinds of events did La Placita Church host for the community over the years?",
        "questionType": "multiple_choice",
        "optionA": "Military ceremonies and political debates",
        "optionB": "Baptisms, weddings, funerals, and community gatherings",
        "optionC": "Trade markets and land auctions",
        "optionD": "Railroad planning meetings and city council sessions",
        "correctAnswer": "b",
        "explanation": "Across multiple political eras, La Placita has hosted baptisms, weddings, funerals, and community gatherings — the rituals that have anchored generations of Latino families near the Plaza.",
        "wrongExplanationA": "La Placita is a parish church, not a political or military venue. Its central role has been in religious and community life.",
        "wrongExplanationC": "Trade and land sales took place in the city's commercial spaces, not inside the parish church. La Placita's role has been ritual and pastoral.",
        "wrongExplanationD": "Civic governance happened in city buildings, not at La Placita. The church's significance is rooted in religious life and the rhythm of family events.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "watts-towers",
    "title": "The Watts Towers and South LA",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What does the source say about Rodia's departure from Los Angeles?",
        "questionType": "multiple_choice",
        "optionA": "He left in 1954 and never returned",
        "optionB": "He returned in 1965 to repair the towers",
        "optionC": "He left because of the uprising",
        "optionD": "He continued building towers elsewhere in California",
        "correctAnswer": "a",
        "explanation": "Rodia left Los Angeles in 1954 — the same year he completed the towers — and never returned. The towers stayed with the neighborhood that came to protect them.",
        "wrongExplanationB": "Rodia did not come back to repair the towers. After he left in 1954, neighbors and preservationists — not Rodia himself — took up their care.",
        "wrongExplanationC": "Rodia left in 1954, more than a decade before the 1965 uprising. The two events are separate in time.",
        "wrongExplanationD": "There is no record of Rodia continuing similar work elsewhere. He left the towers complete and moved on from the project entirely.",
        "orderIndex": 0
      },
      {
        "questionText": "Why did neighbors protect the towers in 1965?",
        "questionType": "multiple_choice",
        "optionA": "They were indifferent to them",
        "optionB": "They saw them as a symbol worth saving",
        "optionC": "They opposed all protests",
        "optionD": "They were untouched by unrest",
        "correctAnswer": "b",
        "explanation": "During the 1965 uprising, neighbors actively shielded the towers because they recognized them as a symbol of creativity, perseverance, and community pride worth saving.",
        "wrongExplanationA": "Indifference would not have led to protection. Neighbors acted because the towers meant something to them.",
        "wrongExplanationC": "The protection of the towers was about valuing what they represented, not about opposing protest. The two are separate questions.",
        "wrongExplanationD": "Watts was at the center of the unrest, not untouched by it. Even amid disruption, residents made a point of preserving the towers.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The 1965 Watts Uprising was only an isolated criminal event.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The uprising was sparked by accumulated tensions over inequality and policing — not an isolated criminal incident. It exposed deeper, structural conditions in South LA.",
        "wrongExplanationA": "Treating the uprising as merely criminal misses the point. It grew out of long-running grievances about inequality and policing, which is why it forced national reckoning.",
        "orderIndex": 2
      },
      {
        "questionText": "What happened to the Watts Towers after the 1965 uprising?",
        "questionType": "multiple_choice",
        "optionA": "They were destroyed during the unrest",
        "optionB": "Rodia returned to repair them",
        "optionC": "The city removed them for safety reasons",
        "optionD": "They survived because neighbors protected them",
        "correctAnswer": "d",
        "explanation": "The towers survived 1965 because neighbors protected them. That act of protection became part of the towers' meaning as a symbol of community pride.",
        "wrongExplanationA": "The towers were not destroyed in 1965 — they came through the uprising intact, thanks to community protection.",
        "wrongExplanationB": "Rodia had left LA in 1954 and never came back. He played no role in the towers' fate during or after the 1965 events.",
        "wrongExplanationC": "The city did not remove the towers. They remained standing, defended by the surrounding neighborhood.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "griffith-observatory",
    "title": "Griffith Park and the Public Observatory",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "Why does the source mention that Griffith intended the park for 'all residents to enjoy'?",
        "questionType": "multiple_choice",
        "optionA": "To show only wealthy people could visit",
        "optionB": "To suggest the gift came with strict private conditions",
        "optionC": "To prove Griffith later regretted his gift",
        "optionD": "To highlight the observatory's public and inclusive purpose",
        "correctAnswer": "d",
        "explanation": "The phrase 'all residents to enjoy' frames Griffith Park and its observatory as a public, inclusive space — open to everyone, with free telescope access from the start.",
        "wrongExplanationA": "The phrase points the opposite way: it stresses that the park was meant for everyone, not just the wealthy.",
        "wrongExplanationB": "The gift was intended as public parkland, not a privately conditioned space. The framing emphasizes openness, not restriction.",
        "wrongExplanationC": "There is no indication Griffith regretted the gift. The phrase highlights the original public intent, not later regret.",
        "orderIndex": 0
      },
      {
        "questionText": "What does the panoramic view from the observatory symbolize?",
        "questionType": "multiple_choice",
        "optionA": "Height is always the truth",
        "optionB": "Seeing many layers of city history at once",
        "optionC": "The observatory is the most important place in LA",
        "optionD": "Only high places matter in history",
        "correctAnswer": "b",
        "explanation": "Looking out over the basin from Griffith Observatory, a viewer can take in centuries of overlapping history at once — Indigenous land, rancho boundaries, modern city — collapsed into a single panorama.",
        "wrongExplanationA": "A high view is not automatically the 'truth' of a place. Its value is letting many overlapping histories be seen together.",
        "wrongExplanationC": "The observatory is significant, but the panorama symbolizes layered history. Treating one place as more important than all others misses the point.",
        "wrongExplanationD": "Low and high places both shape history. The view reveals layers, not a hierarchy of locations.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Telescope viewing at the Griffith Observatory requires paid admission.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. From its 1935 opening, the Griffith Observatory has offered free telescope viewing — fulfilling Griffith's vision of a public space accessible to all residents.",
        "wrongExplanationA": "Charging for telescope access would contradict the observatory's founding intent: a free, public scientific resource for everyone in the city.",
        "orderIndex": 2
      },
      {
        "questionText": "What does the land's layered history reveal?",
        "questionType": "multiple_choice",
        "optionA": "Land has only one meaning at a time",
        "optionB": "Places hold multiple overlapping histories",
        "optionC": "Only rancho history matters in this area",
        "optionD": "Land history is unimportant",
        "correctAnswer": "b",
        "explanation": "The Griffith Observatory's site moved through Indigenous stewardship, Mexican rancho ownership, private speculation, and finally public parkland — a reminder that places hold multiple overlapping histories at once.",
        "wrongExplanationA": "A single place can carry many meanings simultaneously. The observatory's site is exactly the kind of layered space that resists single-meaning readings.",
        "wrongExplanationC": "Rancho history matters, but it is one layer among many — including Indigenous stewardship before it and public parkland after.",
        "wrongExplanationD": "If land history were unimportant, there would be little to learn from places like the observatory. The site's value is precisely in its accumulated histories.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "chavez-ravine",
    "title": "Chavez Ravine: Community, Displacement, and Dodger Stadium",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What does the source say the site of Dodger Stadium remains connected to?",
        "questionType": "multiple_choice",
        "optionA": "Only the excitement of baseball",
        "optionB": "Only the memory of displaced families",
        "optionC": "Both the excitement of baseball and the memory of displaced families",
        "optionD": "Neither, because the site was abandoned",
        "correctAnswer": "c",
        "explanation": "The site holds two truths at once: it is home to a beloved ballpark and to the memory of three displaced communities — Palo Verde, La Loma, and Bishop. Both meanings coexist.",
        "wrongExplanationA": "Limiting the site's meaning to baseball erases the displacement that cleared the land. The two stories belong together.",
        "wrongExplanationB": "Treating the site only as a memorial misses that it is also an active baseball stadium. Both threads of history are present.",
        "wrongExplanationD": "The site is far from abandoned — Dodger Stadium has been in continuous use since 1962. The question is what that use means alongside what came before.",
        "orderIndex": 0
      },
      {
        "questionText": "What happened after the public housing project at Chavez Ravine was canceled?",
        "questionType": "multiple_choice",
        "optionA": "The land sat empty, then was offered to the Brooklyn Dodgers",
        "optionB": "Residents returned to their homes",
        "optionC": "The city built a new school on the site",
        "optionD": "The city gave the land back to displaced families",
        "correctAnswer": "a",
        "explanation": "After cancellation, the cleared land sat empty for years. In 1958, the city offered it to the Brooklyn Dodgers as part of the team's move to Los Angeles, leading eventually to Dodger Stadium.",
        "wrongExplanationB": "Residents could not return — most had already sold their homes under promises of replacement housing that never came.",
        "wrongExplanationC": "No school was built on the cleared site. The land was eventually transferred to the Dodgers, not used for public schools.",
        "wrongExplanationD": "The city did not return the land to displaced families. Instead, it offered the cleared land to a baseball team relocating from Brooklyn.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: Families displaced from Chavez Ravine received the new housing they were promised.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The promised housing project was canceled, leaving displaced families without the replacement homes they had been told to expect.",
        "wrongExplanationA": "Cancellation of the housing project meant the promise went unfulfilled. Families had already given up their homes by the time the project died.",
        "orderIndex": 2
      },
      {
        "questionText": "How does Chavez Ravine connect to Old Chinatown?",
        "questionType": "multiple_choice",
        "optionA": "There is no connection",
        "optionB": "Both communities were removed for major projects",
        "optionC": "Both communities moved voluntarily",
        "optionD": "Both communities benefited equally from displacement",
        "correctAnswer": "b",
        "explanation": "Both Old Chinatown and Chavez Ravine were cleared to make way for major civic projects — Union Station and Dodger Stadium. The pattern of displacing immigrant and working-class communities recurs across LA's twentieth century.",
        "wrongExplanationA": "The two stories share a clear pattern: condemnation, displacement, and a major project replacing a community. Reading them as unconnected misses that pattern.",
        "wrongExplanationC": "Neither community moved voluntarily. Both faced condemnation and displacement they could not refuse.",
        "wrongExplanationD": "Neither community benefited from displacement. The projects that replaced them brought benefits to others, not to the people forced out.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "macarthur-park",
    "title": "MacArthur Park and LA's Immigrant Communities",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What contradictions surface at MacArthur Park?",
        "questionType": "multiple_choice",
        "optionA": "Geography only",
        "optionB": "City ideals versus exclusion and policing",
        "optionC": "Only cultural conflict",
        "optionD": "Beauty versus neglect only",
        "correctAnswer": "b",
        "explanation": "MacArthur Park reveals the gap between civic ideals — public space, freedom of assembly — and the realities of exclusion and aggressive policing experienced by immigrant communities, most starkly in 2007.",
        "wrongExplanationA": "Geography alone doesn't capture the contradiction. The tensions at MacArthur Park are about who gets to use public space and how authority responds to them.",
        "wrongExplanationC": "Cultural conflict is part of the picture, but the deeper contradiction is between stated public ideals and the use of police power against marginalized communities.",
        "wrongExplanationD": "Beauty versus neglect is too narrow. The 2007 rally shows the contradiction is also about civic ideals versus exclusionary enforcement.",
        "orderIndex": 0
      },
      {
        "questionText": "Why does the source mention that Central American refugees settled near MacArthur Park by the 1980s?",
        "questionType": "multiple_choice",
        "optionA": "To show that the park became abandoned",
        "optionB": "To prove only one group used the park",
        "optionC": "To argue that refugees avoided the park",
        "optionD": "To explain that the park was shaped by many cultures, including commerce and daily life",
        "correctAnswer": "d",
        "explanation": "Central American refugee settlement around the park transformed surrounding neighborhoods. The park became a hub of commerce, gathering, and daily life — shaped by many cultures together.",
        "wrongExplanationA": "Far from being abandoned, the park became more central to community life as the surrounding neighborhood grew dense with new arrivals.",
        "wrongExplanationB": "MacArthur Park has long been used by many groups. The point of mentioning the 1980s wave is layered settlement, not exclusive use.",
        "wrongExplanationC": "Refugees did not avoid the park — they made it part of daily life. The source highlights settlement and use, not avoidance.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: MacArthur Park was always a working-class immigrant neighborhood.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The area began as an upscale destination ringed by luxury hotels and fashionable neighborhoods. Its transformation into a working-class immigrant hub came only as Los Angeles expanded outward.",
        "wrongExplanationA": "MacArthur Park's earliest decades attracted wealthy residents and luxury hotels. Its identity as a working-class immigrant area emerged through later demographic change.",
        "orderIndex": 2
      },
      {
        "questionText": "How does the 2007 rally response connect to other histories?",
        "questionType": "multiple_choice",
        "optionA": "It was an isolated event",
        "optionB": "It reflects recurring suppression of marginalized communities",
        "optionC": "It had no significance beyond the day itself",
        "optionD": "It was unrelated to immigration history",
        "correctAnswer": "b",
        "explanation": "The 2007 police response fits a longer pattern in LA history: marginalized communities — from Old Chinatown to Chavez Ravine to MacArthur Park — experiencing suppression when they assert their place in public life.",
        "wrongExplanationA": "Treating the event as isolated misses the pattern. It echoes earlier moments of force used against marginalized communities in the city.",
        "wrongExplanationC": "The day shaped national debate about policing and protest. Its significance reaches well beyond the immediate event.",
        "wrongExplanationD": "The rally was specifically about immigration rights, and the violent response targeted an immigrant-rooted community gathered in public space — the connection to immigration history is direct.",
        "orderIndex": 3
      }
    ]
  },
  {
    "locationSlug": "hollywood-sign",
    "title": "The Hollywood Sign and the Film Industry",
    "passingScore": 70,
    "pointsReward": 50,
    "questions": [
      {
        "questionText": "What 'truth' did the sign eventually come to represent?",
        "questionType": "multiple_choice",
        "optionA": "Ads are always false",
        "optionB": "Los Angeles can transform itself beyond its commercial origins",
        "optionC": "Film is more honest than real estate",
        "optionD": "Old signs are inherently truthful",
        "correctAnswer": "b",
        "explanation": "A real estate billboard for a housing development became, over time, a global symbol of fame, reinvention, and entertainment. The sign embodies LA's tendency to transform itself far beyond what it originally claimed to be.",
        "wrongExplanationA": "The sign isn't really about advertising being false — it's about a commercial object outgrowing its original purpose to mean something larger.",
        "wrongExplanationC": "Pitting film against real estate misses the point. The sign came from real estate and became a film icon, showing transformation rather than contrast.",
        "wrongExplanationD": "Age alone doesn't make a sign truthful. What matters here is how the sign's meaning shifted, not how long it has stood.",
        "orderIndex": 0
      },
      {
        "questionText": "What happened to the Hollywood Sign in the 1970s?",
        "questionType": "multiple_choice",
        "optionA": "It fell into disrepair, then was replaced through a fundraising campaign in 1978",
        "optionB": "The film industry abandoned it",
        "optionC": "It was moved to a different mountain",
        "optionD": "It was demolished permanently",
        "correctAnswer": "a",
        "explanation": "By the 1970s the sign had badly deteriorated. A 1978 fundraising campaign replaced the letters, restoring the landmark for the decades that followed.",
        "wrongExplanationB": "The film industry didn't abandon the sign — quite the opposite, since by the 1970s the sign had become tightly identified with Hollywood itself.",
        "wrongExplanationC": "The sign has stayed on Mount Lee throughout its history. It was repaired in place, not relocated.",
        "wrongExplanationD": "The sign was not demolished — the 1978 campaign rebuilt it. It still stands today as one of the most photographed landmarks in the world.",
        "orderIndex": 1
      },
      {
        "questionText": "True or False: The sign was originally intended as a permanent civic landmark.",
        "questionType": "true_false",
        "optionA": "True",
        "optionB": "False",
        "correctAnswer": "b",
        "explanation": "False. The sign was built as a temporary advertisement for a housing development. Its civic and global meaning came later, as Hollywood's identity grew.",
        "wrongExplanationA": "The sign was a real estate ad, not a civic monument. It became permanent and iconic by accident of cultural history, not original design.",
        "orderIndex": 2
      },
      {
        "questionText": "What was the original purpose of the Hollywoodland sign in 1923?",
        "questionType": "multiple_choice",
        "optionA": "A civic monument to the film industry",
        "optionB": "A tribute to silent film stars",
        "optionC": "A welcome sign for tourists",
        "optionD": "An advertisement for a housing development",
        "correctAnswer": "d",
        "explanation": "The original 'HOLLYWOODLAND' sign was an advertisement for a hillside housing development. Its later identity as a film-industry symbol was an unintended afterlife.",
        "wrongExplanationA": "Civic recognition of the film industry came later. In 1923 the sign was simply real estate marketing — its civic meaning grew over time.",
        "wrongExplanationB": "The sign did not honor specific film stars. It promoted a real estate subdivision and only later took on cultural meaning.",
        "wrongExplanationC": "The sign was not built to greet tourists — it was meant to attract home buyers to a specific hillside development.",
        "orderIndex": 3
      }
    ]
  }
] as const satisfies readonly Quiz[];

export const quizzesByLocationSlug = new Map(quizzes.map((q) => [q.locationSlug, q]));
